name: con
channels:
- defaults
dependencies:
- filelock=3.16.1
- fsspec=2024.9.0
- jinja2=3.1.4
- joblib=1.4.2
- markupsafe=2.1.5
- mpmath=1.3.0
- networkx=3.3
- numpy=2.1.1
- pillow=10.4.0
- scikit-learn=1.5.2
- scipy=1.14.1
- sympy=1.13.3
- threadpoolctl=3.5.0
- torch=2.4.1
- torchvision=0.19.1
- tqdm=4.66.5
- typing-extensions=4.12.2
- python=3.11
