name: con
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.10
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.16.1
      - fonttools==4.55.0
      - fsspec==2024.10.0
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mizani==0.13.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.1.3
      - packaging==24.2
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.0.0
      - plotnine==0.14.1
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - scipy==1.14.1
      - six==1.16.0
      - statsmodels==0.14.4
      - sympy==1.13.1
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
