name: con
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.9
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.6
      - aiosignal==1.3.1
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - datasets==2.14.4
      - dill==0.3.7
      - filelock==3.16.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - huggingface-hub==0.25.1
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.4.2
      - lightning-utilities==0.11.7
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.15
      - networkx==3.3
      - numpy==2.1.1
      - packaging==24.1
      - pandas==2.2.3
      - pillow==10.4.0
      - pyarrow==17.0.0
      - pynvml==11.5.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - six==1.16.0
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - torch==2.4.1
      - torchmetrics==1.4.2
      - torchvision==0.19.1
      - tqdm==4.66.5
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - xxhash==3.5.0
      - yarl==1.12.1
